name: Test GNU/GNU+DEV Build 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-gnu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the GNU Docker image
      run: docker build . --file gnu.Dockerfile -t robcking/eddy_builder:gnu_mpich

    - uses: actions/checkout@v4
    - name: Build the GNU Docker image (openmpi)
      run: docker build . --file gnu_openmpi.Dockerfile -t robcking/eddy_builder:gnu_openmpi

    - name: Build the GNU+DEV Docker image
      run: docker build . --file gnu_dev.Dockerfile -t robcking/eddy_builder_dev:gnu_mpich

    - uses: actions/checkout@v4
    - name: Build the GNUDEV Docker image (openmpi)
      run: docker build . --file gnu_dev_openmpi.Dockerfile -t robcking/eddy_builder_dev:gnu_opempi
