name: Test Intel Build 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-intel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file intel.Dockerfile -t robcking/eddy-builder